image: maven:latest

variables:
  SMR_STAGE: "DEV"
  AWS_ACCESS_KEY_ID: "123"
  AWS_SECRET_ACCESS_KEY: "123"
  AWS_DEFAULT_REGION: "eu-west-1"

stages:
  - build

build_library_job:
  stage: build
  script:
    - "apt update"
    - "apt -y install rubygems python3-pip"
    - "gem install fakes3"
    - "fakes3 -r /mnt/fakes3_root -p 4567 > /dev/null 2>&1 &"
    - "cd serverless-mapreduce"
    - "mvn package"
    - "mvn -e org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=target/serverless_mapreduce.jar -DgroupId=fr.d2si -DartifactId=serverless_mapreduce -Dversion=0.0.1 -Dpackaging=jar -DlocalRepositoryPath=${HOME}/.m2/repository/"
    - "cd ../example-project"
    - "./package.sh"
